# Generated by Django 5.2.4 on 2025-12-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0016_remove_userconfirmation_client_ip_confirmed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangoimage',
            name='client_ip',
        ),
        migrations.RemoveField(
            model_name='predictionlog',
            name='client_ip',
        ),
    ]
