# Generated by Django - Remove is_correct field from UserConfirmation

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0017_remove_client_ip_from_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfirmation',
            name='is_correct',
        ),
    ]
