# Generated by Django 5.2.4 on 2026-02-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0018_remove_userconfirmation_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='postal_code',
        ),
    ]
