# Generated by Django 5.2.4 on 2026-02-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0020_modelconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='detection_type',
            field=models.CharField(choices=[('leaf', 'Leaf Disease Model'), ('fruit', 'Fruit Disease Model'), ('gate_leaf', 'Gate Leaf Model'), ('gate_fruit', 'Gate Fruit Model')], max_length=20, unique=True),
        ),
    ]
