# Generated by Django 5.2.4 on 2026-04-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0021_alter_modelconfig_detection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangoimage',
            name='training_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mangoimage',
            name='training_ready',
            field=models.BooleanField(default=False),
        ),
    ]
