# Generated by Django 5.2.4 on 2026-04-26 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0022_mangoimage_training_notes_mangoimage_training_ready'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='readable disease name matching LEAF_CLASS_NAMES / FRUIT_CLASS_NAMES.', max_length=100)),
                ('plant_part', models.CharField(choices=[('leaf', 'Leaf'), ('fruit', 'Fruit')], max_length=10)),
                ('is_in_classifier', models.BooleanField(default=False, help_text='True if this disease is a valid prediction label in the current trained XGBoost / CNN models.')),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
                'ordering': ['plant_part', 'name'],
                'unique_together': {('name', 'plant_part')},
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Canonical snake_case key, e.g. 'dark_spots_brown'.", max_length=80)),
                ('plant_part', models.CharField(choices=[('leaf', 'Leaf'), ('fruit', 'Fruit')], help_text='Which part of the plant this symptom describes.', max_length=10)),
                ('vector_index', models.PositiveSmallIntegerField(blank=True, help_text='Column index in the XGBoost feature vector. None for symptoms outside the classifier vocabulary.', null=True)),
                ('is_in_vocabulary', models.BooleanField(default=False, help_text='True if this key appears in LEAF_SYMPTOMS or FRUIT_SYMPTOMS and is a valid XGBoost feature. False for display-only keys.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Symptoms',
                'ordering': ['plant_part', 'vector_index', 'key'],
                'unique_together': {('key', 'plant_part')},
            },
        ),
        migrations.CreateModel(
            name='SymptomAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(help_text='The variant / legacy string that will be resolved.', max_length=120, unique=True)),
                ('source', models.CharField(blank=True, help_text='Helps auditors trace where ', max_length=200)),
                ('canonical', models.ForeignKey(help_text='The canonical symptom this alias resolves to.', on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='mangosense.symptom')),
            ],
            options={
                'verbose_name': 'Symptom Alias',
                'verbose_name_plural': 'Symptom Aliases',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_label', models.CharField(help_text='Verbose UI string shown to the user in the mobile symptom checklist.', max_length=300)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text="Sort order within the disease's symptom list (0-based).")),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_symproms', to='mangosense.disease')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disease_symptoms', to='mangosense.symptom')),
            ],
            options={
                'verbose_name': 'Disease–Symptom Link',
                'verbose_name_plural': 'Disease–Symptom Links',
                'ordering': ['disease', 'display_order'],
                'unique_together': {('disease', 'display_order')},
            },
        ),
    ]
