# Generated by Django 5.2.4 on 2026-05-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0024_seed_symptom_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Brief description of the disease shown to users.'),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment',
            field=models.TextField(blank=True, default='', help_text='Treatment / management advice returned by the prediction API.'),
        ),
    ]
